name: rate_my_app
description: Allows to kindly ask users to rate your app if custom conditions are met (eg. install time, number of launches, etc...).
version: 0.5.1
homepage: https://github.com/Skyost/rate_my_app

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  shared_preferences: '>=0.5.7 <2.0.0'
  smooth_star_rating: ^1.1.1
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: fr.skyost.rate_my_app
    pluginClass: RateMyAppPlugin
